// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mndgdlshrfjennytrlmy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1uZGdkbHNocmZqZW5ueXRybG15Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1MDY0NTQsImV4cCI6MjA2NTA4MjQ1NH0.uIZeS4mSYixWsaTdyt_KP0Mdc5ImJCb3sqSilR0UtTA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);